# Generated by Django 2.2.8 on 2020-02-03 15:18

import awx.main.models.ha
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_v370_remove_jobevent_parent_and_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='routable_hostname',
            field=models.CharField(default=awx.main.models.ha.Instance.routable_hostname_default, max_length=250, unique=True),
        ),
    ]
