# Generated by Django 2.2.16 on 2020-11-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_delete_toweranalyticsstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjob',
            name='time_on_cpu',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='unifiedjob',
            name='time_waiting_for_cpu',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
