# Generated by Django 4.2.6 on 2024-03-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0189_inbound_hop_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjob',
            name='job_lifecycle_id',
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                help_text='The most recent (last) span id of the job lifecycle while in Django.',
                max_length=255,
                null=True,
            ),
        ),
    ]
