version: '2'
services:
  haproxy:
    build:
      context: ./docker-compose
      dockerfile: Dockerfile-haproxy
    container_name: tools_haproxy_1
    depends_on:
      - "awx_1"
      - "awx_2"
      - "awx_3"
    ports:
      - "8013:8013"
      - "8043:8043"
      - "1936:1936"
      - "15672:15672"
  awx_1:
    user: ${CURRENT_UID}
    container_name: tools_awx_1_1
    privileged: true
    image: ${DEV_DOCKER_TAG_BASE}/awx_devel:${TAG}
    hostname: awx_1
    #entrypoint: ["bash"]
    environment:
      CURRENT_UID:
      SENTINEL_HOST: "sentinel_1"
      SENTINEL_PORT: "63794"
      SDB_HOST: 0.0.0.0
      SDB_PORT: 5899
      AWX_GROUP_QUEUES: alpha,tower
    command: /start_development.sh
    working_dir: "/awx_devel"
    volumes:
      - "../:/awx_devel"
    ports:
      - "5899-5999:5899-5999"
  awx_2:
    user: ${CURRENT_UID}
    container_name: tools_awx_2_1
    privileged: true
    image: ${DEV_DOCKER_TAG_BASE}/awx_devel:${TAG}
    hostname: awx_2
    command: /start_development.sh
    working_dir: "/awx_devel"
    environment:
      CURRENT_UID:
      SENTINEL_HOST: "sentinel_2"
      SENTINEL_PORT: "63795"
      SDB_HOST: 0.0.0.0
      SDB_PORT: 7899
      AWX_GROUP_QUEUES: bravo,tower
    volumes:
      - "../:/awx_devel"
    ports:
      - "7899-7999:7899-7999"
  awx_3:
    user: ${CURRENT_UID}
    container_name: tools_awx_3_1
    privileged: true
    image: ${DEV_DOCKER_TAG_BASE}/awx_devel:${TAG}
    hostname: awx_3
    entrypoint: ["bash"]
    command: /start_development.sh
    working_dir: "/awx_devel"
    environment:
      CURRENT_UID:
      SENTINEL_HOST: "sentinel_3"
      SENTINEL_PORT: "63796"
      SDB_HOST: 0.0.0.0
      SDB_PORT: 8899
      AWX_GROUP_QUEUES: charlie,tower
    volumes:
      - "../:/awx_devel"
    ports:
      - "8899-8999:8899-8999"
  redis_1:
    image: redis:latest
    hostname: redis_1
    container_name: tools_redis_1_1
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - "./redis/redis-master.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - "63791:63791"
  redis_2:
    image: redis:latest
    hostname: redis_2
    container_name: tools_redis_2_1
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - "./redis/redis-slave_1.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - "63792:63792"
  redis_3:
    image: redis:latest
    hostname: redis_3
    container_name: tools_redis_3_1
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - "./redis/redis-slave_2.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - "63793:63793"
  sentinel_1:
    user: ${CURRENT_UID}
    image: redis:latest
    hostname: sentinel_1
    container_name: tools_sentinel_1_1
    command: "redis-server /usr/local/etc/redis/sentinel.conf --sentinel"
    volumes:
      - "./sentinel/sentinel_1.conf:/usr/local/etc/redis/sentinel.conf"
    ports:
      - "63794:63794"
  sentinel_2:
    user: ${CURRENT_UID}
    image: redis:latest
    hostname: sentinel_2
    container_name: tools_sentinel_2_1
    command: "redis-server /usr/local/etc/redis/sentinel.conf --sentinel"
    volumes:
      - "./sentinel/sentinel_2.conf:/usr/local/etc/redis/sentinel.conf"
    ports:
      - "63795:63795"
  sentinel_3:
    user: ${CURRENT_UID}
    image: redis:latest
    hostname: sentinel_3
    container_name: tools_sentinel_3_1
    command: "redis-server /usr/local/etc/redis/sentinel.conf --sentinel"
    volumes:
      - "./sentinel/sentinel_3.conf:/usr/local/etc/redis/sentinel.conf"
    ports:
      - "63796:63796"
  postgres:
    image: postgres:10
    container_name: tools_postgres_1
  memcached:
    image: memcached:alpine
    container_name: tools_memcached_1
